### ISSUE TITLE
Parchear las imágenes a tamaños introducibles a la red YOLOv5

### ISSUE THREAD

**Issue by xFranv8** [xFranv8/AIVA_2023_COCHES#1]
Se deben parchear las imágenes antes de pasarlas por la red YOLOv5 debido a su gran resolución.

**Comment by brodgon** [comment]
Una vez terminado el proyecto piloto de CarDensityAI se asignan tiempos a cada tarea.  En este caso, se estimo que la tarea de parcheado conllevaría 5h. Debido al uso de métodos ya implementados,  el tiempo de esta tarea se redujo a 2h (incluyendo comprensión del sistema e implementación).
