### ISSUE TITLE
Entrenar YOLT

### ISSUE THREAD

**Issue by xFranv8** [xFranv8/AIVA_2023_COCHES#4]
Entrenaremos una red YOLT con las imágenes proporcionadas por el cliente, y si es necesario, se buscarán otras bases de datos open source similares para entrenar.

**Comment by brodgon** [comment]
Durante el desarrollo del proyecto hemos decido trabajar con una YOLO pre-entrenada en lugar de emplear la red YOLT. Se da por terminada/descartada esta issue.
