### ISSUE TITLE
Crear frontend web con Django

### ISSUE THREAD

**Issue by xFranv8** [xFranv8/AIVA_2023_COCHES#5]
Se creará un portal web al que los usuarios subirán las imágenes para analizarlas.

**Comment by brodgon** [comment]
Una vez terminado el proyecto piloto de CarDensityAI se asignan tiempos a cada tarea.  En este caso, se estimo que la tarea de creación del frontend web llevaría 1 día completo. Debido a conocimientos previos en esta tárea, el tiempo de desarrollo se redujo a 6h.
