### ISSUE TITLE
Realizar test sobre el mockup principal del sistema

### ISSUE THREAD

**Issue by xFranv8** [xFranv8/AIVA_2023_COCHES#6]
Se realizarán test sobre las funciones de "subir imagen" , de dividir una imagen en subimagenes mas pequeñas y de la reconstruccion de una imagen a partir de otras pequeñas.

**Comment by brodgon** [comment]
Una vez terminado el proyecto piloto de CarDensityAI se asignan tiempos a cada tarea.  En este caso, se estimó que el diseño total de tests sobre el código de la aplicación cubriría todo el periodo de diseño del sistema ya que se desarrollan a la par. De manera aproximada, se estima que la tarea se resuelve en alrededor 2 semanas (a pesar de que no se dedica el tiempo completo a esta tarea).
