### ISSUE TITLE
Añadir "output_path" como parámetro de entrada al algoritmo

### ISSUE THREAD

**Issue by xFranv8** [xFranv8/AIVA_2023_COCHES#9]

**Comment by brodgon** [comment]
Tras la inferencia de resultados sobre una de las imágenes se divisó un problema. Precisamente,  nos damos cuenta de que el usuario no puede elegir el directorio donde se guarda el resultado. Este problema se solventa de forma rápida, no ocupando más de 1h de desarrollo.
